// <auto-generated />
using System;
using Kutuphane.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kutuphane.DataAccess.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20260123031052_StokEklendi")]
    partial class StokEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kutuphane.Entities.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<int>("ISBN")
                        .HasColumnType("integer")
                        .HasColumnName("isbn");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategori");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("sayfa_sayisi");

                    b.Property<int>("Stok")
                        .HasColumnType("integer")
                        .HasColumnName("stok");

                    b.Property<string>("YayinEvi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yayin_evi");

                    b.Property<int>("YayinYili")
                        .HasColumnType("integer")
                        .HasColumnName("yayin_yili");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yazar");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar", (string)null);
                });

            modelBuilder.Entity("Kutuphane.Entities.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kayit_tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soyad");

                    b.Property<int>("TcNo")
                        .HasColumnType("integer")
                        .HasColumnName("tc_no");

                    b.Property<int>("TelefonNumarasi")
                        .HasColumnType("integer")
                        .HasColumnName("telefon_numarasi");

                    b.HasKey("Id");

                    b.ToTable("Uyeler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
