// <auto-generated />
using System;
using Kutuphane.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kutuphane.DataAccess.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20260125023605_OduncIslemYaratıldı")]
    partial class OduncIslemYaratıldı
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kutuphane.Entities.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<int>("ISBN")
                        .HasColumnType("integer")
                        .HasColumnName("isbn");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kategori");

                    b.Property<int>("SayfaSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("sayfa_sayisi");

                    b.Property<int>("Stok")
                        .HasColumnType("integer")
                        .HasColumnName("stok");

                    b.Property<string>("YayinEvi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yayin_evi");

                    b.Property<int>("YayinYili")
                        .HasColumnType("integer")
                        .HasColumnName("yayin_yili");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("yazar");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar", (string)null);
                });

            modelBuilder.Entity("Kutuphane.Entities.OduncIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GecikmeGunSayisi")
                        .HasColumnType("integer");

                    b.Property<bool>("IadeEdildiMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KitapId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonIadeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UyeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("UyeId");

                    b.ToTable("OduncIslem");
                });

            modelBuilder.Entity("Kutuphane.Entities.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kayit_tarihi");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("soyad");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("tc_no");

                    b.Property<string>("TelefonNumarasi")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("telefon_numarasi");

                    b.HasKey("Id");

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("Kutuphane.Entities.OduncIslem", b =>
                {
                    b.HasOne("Kutuphane.Entities.Kitap", "Kitap")
                        .WithMany("OduncIslemler")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Entities.Uye", "Uye")
                        .WithMany("OduncIslemler")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("Kutuphane.Entities.Kitap", b =>
                {
                    b.Navigation("OduncIslemler");
                });

            modelBuilder.Entity("Kutuphane.Entities.Uye", b =>
                {
                    b.Navigation("OduncIslemler");
                });
#pragma warning restore 612, 618
        }
    }
}
